### ISSUE TITLE
登录接口超时

### ISSUE THREAD

**Issue by TakWolf** [LNTUORG/LNTUOnline-API-Nodejs#11]
登录接口，如果密码填写错误，有较大几率出现请求无响应最终超时。

**Comment by pupboss** [comment]
没有哇，我这立即返回400错误

```
HTTP/1.1 400 Bad Request
Server: nginx
Date: Tue, 12 Apr 2016 02:18:59 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 52
Connection: close
ETag: W/"34-RJdUO5jV4O55iqIVYabWvQ"
Vary: Accept-Encoding

{"code":"PASSWORD_ERROR","message":"password error"}
```

**Comment by TakWolf** [comment]
我这里测试是这样的，输入正确的密码响应非常快。
如果密码错误，只有很小一部分可以立刻返回。大部分最后都会变成超时

**Comment by pupboss** [comment]
```
      if (err) {
        return callback(constant.cookie.net_error, null);
      }
      var result = res.redirects[0];
      if (result.indexOf('frameset.jsp') > 0) {
        result = result.replace(constant.urls[base_url_index] + 'frameset.jsp;jsessionid=', '');
        return callback(null, result);
      } else {
        return callback(constant.cookie.user_error, null);
      }
```

第一个 cb 是如果有网络故障，肯定触发，如果网络没有故障，一定会有 res，再判断 res 里面包不包含登录成功的标识，理论上都不会有超时，回头我再多测试几次。

对了你是在安卓测试的还是别的工具

**Comment by TakWolf** [comment]
已经测试过了，这个问题应该就是跟你配置的http2有关系。

不只是密码输入错误，就是输入正确的密码，也有可能出现这个问题。表现是最终是有结果的，但是响应超极慢，平均达到1分多，但是有小概率会直接返回。跟网络线路没关系。

这个问题目前只表现在Android 5.x以上（包括Android 6.0, Android N模拟器环境）,这些设备跟踪日志发现调用的时候客户端协议会升级到http2

手里的Android 4.4 、Android 4.0、Android 2.3没这个问题，跟踪发现使用的是http1
iOS手里的两个设备都没这个问题，分别是iphone6sp iOS9.3, itouch iOS9.3，具体走的协议是什么不清楚。

本地直接跑和通过mockwebserver搭建模拟的http2server访问正常。

不太了解你线上的部署情况，这个现象是最近才发现的（我不确定是不是后台更好成node之后并行出现的，当时没有详细测试）。你检查一下跟http2相关的东西。

**Comment by pupboss** [comment]
服务器是用的 Nginx，负责转发请求给 localhost:port，之前的 java 也是这样运行，iOS 客户端也是走的 HTTP/2.0，iOS9 以上，八成还是跟 Nginx  的配置有关，Nginx 我一直用的主线版，平均一个月更新一次，对了，Nginx 我是自己编译的，加入了 CT 模块，和 openssl 的 ChaCha20 支持....应该都是有可能造成这个问题的。安卓那边要不试试把网络库更新成最新的，再不行的话下次 Nginx 更新我不自己编译了，就用源里面的
