### ISSUE TITLE
Licence调整为AGPL

### ISSUE THREAD

**Issue by TakWolf** [LNTUORG/LNTUOnline-API-Nodejs#20]
理由详见：

https://zh.wikipedia.org/wiki/Affero%E9%80%9A%E7%94%A8%E5%85%AC%E5%85%B1%E8%AE%B8%E5%8F%AF%E8%AF%81

http://www.gnu.org/licenses/agpl-3.0.txt

**Comment by pupboss** [comment]
好的！
